# Generated by Django 5.0.7 on 2024-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='Articles'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Categories'),
        ),
    ]
