# Generated by Django 5.0.7 on 2024-07-18 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0002_remove_article_slug_alter_article_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'article_id')},
        ),
        migrations.AddField(
            model_name='rating',
            name='vote',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='values',
        ),
    ]
