# Generated by Django 5.0.7 on 2024-07-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0003_alter_rating_options_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
