# Generated by Django 5.0.7 on 2024-07-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_post', '0003_alter_rating_options_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_post.article')),
            ],
        ),
    ]
